# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('attending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_number', models.IntegerField(primary_key=True, serialize=False)),
                ('invite_amount', models.IntegerField()),
                ('invite_owner', models.CharField(choices=[('TAMSIN', 'TAMSIN'), ('JOASH', 'JOASH')], db_index=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.Invite'),
        ),
    ]
